### ISSUE TITLE
SVG Problems!

### ISSUE THREAD

**Issue by athif23** [mebble/intervals#2]
I have been trying to help out with this project for a while, but I have one issue, I don't have any pause svg. Can you tell me where do you get all this svg from? Or do you create it on your own?

**Comment by mebble** [comment]
Thanks for wanting to help out! I got the svgs from icomoon. Just use the developer tools to copy the path property of the svg element of the icon.

**Comment by mebble** [comment]
Check out [this article](https://medium.com/@david.gilbertson/icons-as-react-components-de3e33cb8792) that I got the idea from

**Comment by athif23** [comment]
Thanks.
